//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public Batch()
        {
            this.SM_Class = new HashSet<SM_Class>();
        }
    
        public int Id { get; set; }
        public int BoardId { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual ICollection<SM_Class> SM_Class { get; set; }
    }
}
