//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hostel
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public int InstitutionId { get; set; }
        public string Superintendent { get; set; }
    
        public virtual Institution Institution { get; set; }
    }
}
