//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public Institution()
        {
            this.Department = new HashSet<Department>();
            this.Hostel = new HashSet<Hostel>();
            this.Board = new HashSet<Board>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string web_address { get; set; }
        public string Address { get; set; }
        public string Contact_number { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
    
        public virtual ICollection<Department> Department { get; set; }
        public virtual ICollection<Hostel> Hostel { get; set; }
        public virtual ICollection<Board> Board { get; set; }
    }
}
