//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Batch
{
    public Batch()
    {
        this.SM_Class = new HashSet<SM_Class>();
    }

    public int Id { get; set; }
    public int BoardId { get; set; }

    public virtual Board Board { get; set; }
    public virtual ICollection<SM_Class> SM_Class { get; set; }
}

public partial class Board
{
    public Board()
    {
        this.Batch = new HashSet<Batch>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public int InstitutionId { get; set; }

    public virtual ICollection<Batch> Batch { get; set; }
    public virtual Institution Institution { get; set; }
}

public partial class Department
{
    public int Id { get; set; }
    public int InstitutionId { get; set; }
    public string Name { get; set; }
    public string HOD { get; set; }

    public virtual Institution Institution { get; set; }
}

public partial class Hostel
{
    public int Id { get; set; }
    public string Address { get; set; }
    public int InstitutionId { get; set; }
    public string Superintendent { get; set; }

    public virtual Institution Institution { get; set; }
}

public partial class Institution
{
    public Institution()
    {
        this.Department = new HashSet<Department>();
        this.Hostel = new HashSet<Hostel>();
        this.Board = new HashSet<Board>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string web_address { get; set; }
    public string Address { get; set; }
    public string Contact_number { get; set; }
    public string State { get; set; }
    public string City { get; set; }
    public string PostalCode { get; set; }

    public virtual ICollection<Department> Department { get; set; }
    public virtual ICollection<Hostel> Hostel { get; set; }
    public virtual ICollection<Board> Board { get; set; }
}

public partial class Section
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int SM_ClassId { get; set; }

    public virtual SM_Class SM_Class { get; set; }
}

public partial class SM_Class
{
    public SM_Class()
    {
        this.Section = new HashSet<Section>();
        this.Subject = new HashSet<Subject>();
    }

    public int Id { get; set; }
    public int BoardId { get; set; }
    public int BatchId { get; set; }

    public virtual ICollection<Section> Section { get; set; }
    public virtual Batch Batch { get; set; }
    public virtual ICollection<Subject> Subject { get; set; }
}

public partial class Subject
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int SM_ClassId { get; set; }

    public virtual SM_Class SM_Class { get; set; }
}
