//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class SchoolModelContainer : DbContext
{
    public SchoolModelContainer()
        : base("name=SchoolModelContainer")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Institution> InstitutionSet { get; set; }
    public virtual DbSet<Board> BoardSet { get; set; }
    public virtual DbSet<Section> SectionSet { get; set; }
    public virtual DbSet<Department> DepartmentSet { get; set; }
    public virtual DbSet<Hostel> HostelSet { get; set; }
    public virtual DbSet<SM_Class> SM_ClassSet { get; set; }
    public virtual DbSet<Subject> SubjectSet { get; set; }
    public virtual DbSet<Batch> BatchSet { get; set; }
}
