//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_Class
    {
        public SM_Class()
        {
            this.Section = new HashSet<Section>();
            this.Subject = new HashSet<Subject>();
        }
    
        public int Id { get; set; }
        public int BoardId { get; set; }
        public int BatchId { get; set; }
    
        public virtual ICollection<Section> Section { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual ICollection<Subject> Subject { get; set; }
    }
}
